@extends('main')
@section('body')
    



<div class="top-header">
	<img class="desktop" src="{{asset('images/uu1.jpg')}}" alt="Learn about Solar Power" title="Learn about Solar Power">
    <img class="mob" src="{{asset('images/uu1.jpg')}}" alt="Learn about Solar Power" title="Learn about Solar Power" style="height:280px;">
</div>
<div class="clear"></div>

<div class="wrapper">
    <div class="gap50"></div>
    <div class="clear"></div>
    <div class="about-box2">

         <CENTER>
    <div class="right-box" style="width: 100%; float: none; padding-left: 0px;">
        	<div class="learn-about-solar">
            	<h2>WHY SOLAR ?</h2>
                <p>Enough sunlight reaches the earth in one hour to power the world for an entire year. Unlike the substantial resources and capital needed to extract and burn fossil fuels, anyone can purchase and install solar panels to take advantage of this abundance of sunlight. Best of all, solar generates significant long-term savings on electricity bills.</p>

            </div>
        </div>
    </CENTER>
    </div>
</div>

<!-- about -->
<div class="about-w3l" id="about">
  <div class="container">
    <div class="about-main-w3l">
    
      <div class="about-bottom-w3l">
        <div class="col-md-4 about-grid">
          <div class="about-grid-main">
            <h4 style="margin-top: -30px;">Save on electricity bills</h4>
            <p style="margin-bottom: -23px;">Installing solar panels reduces electricity bills and dependence on the power grid. This energy independence protects against rising electricity costs and volatile fuel prices. With increases in electricity rates, solar remains a cost-effective solution and long-term investment in the future.</p>

          </div>
        </div>
        <div class="col-md-4 about-grid">
          <div class="about-grid-main">
            <h4 style="margin-top: -30px;">Increase property value</h4>
            <p style="margin-bottom: 10px;">Studies have shown properties with solar systems sell up to 20 percent faster and at a 17 percent premium compared to homes without such systems. A solar installation makes your property more attractive to buyers so its easy to sell it also increasing its resale value.</p>
          </div>
        </div>
        <div class="col-md-4 about-grid">
          <div class="about-grid-main">
            <h4 style="margin-top: -30px;">Reduce your carbon footprint</h4>
            <p style="margin-bottom: -15px;">Unlike energy generated by fossil fuels, solar doesn’t release harmful carbon dioxide (CO2) emission. Sustainable carbon-free energy solutions such as solar are crucial to slowing the pace of climate change and preventing further damage to the environment.
            <br> </p>
          </div>
        </div>
        <div class="clearfix"> </div>
      </div>      
        


    </div>
  </div>
</div>
<!-- about -->

<div class="wrapper">
    <div class="gap50"></div>
    <div class="clear"></div>
    <div class="about-box2">
       




         <CENTER>
    <div class="right-box" style="width: 100%; float: none; padding-left: 0px;">
          <div class="learn-about-solar">             
                <h2>SOLAR POWER</h2>
                <p>Unlike traditional energy sources, the sun produces enough energy each second to sustain our power needs for 500,000 years!</p>
                <p>The continuous emission of energy isn’t the only positive aspect of incorporating solar power for your requirements.</p>
                <div class="use-solar-row">
                  <div class="use-solar-col">
                      <span>
                          <strong>Economically sensible</strong>
                            <small>There are 0 recurring costs on solar power supply.</small>
                        </span> 
                    </div>
                    <div class="use-solar-col">
                      <span>
                          <strong>Environmentally sustainable</strong>
                            <small>Solar power will not run-out like traditional power sources such as fossil fuels.</small>
                        </span> 
                    </div>
                </div>
                <div class="food-for-thought-row">
                    <div class="left-col">
                        <big>Food <br>for thought</big>
                        <small>1kW Solar power saves -</small>
                    </div>
                    <div class="right-col">
                        <ul>
                            <li>77 kg coal <span>from being burned</span></li>
                            <li>397 litres <span>of water consumption</span></li>
                            <li>136 kg of CO<sub>2</sub> <span>being released into <br>the atmosphere</span></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </CENTER>
    </div>
<div class="clear"></div>
</div>


<script type="text/javascript" src="{{asset('wp-content/themes/tpsolar/assets/js/nav.js')}}"> </script>
<script type='text/javascript' src="{{asset('wp-includes/js/wp-embed.min1845.js?ver=4.9.6')}}"></script>



@endsection